A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('', include('products.urls', namespace='products')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('orders.urls', namespace='orders')),
    path('verification/', include('verify_email.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='accounts_register'),
    path('login/', views.UserLoginView.as_view(), name='accounts_login'),
    path('logout/', views.UserLogoutView.as_view(), name='accounts_logout'),
    path('profile/', views.UserProfileView.as_view(), name='accounts_profile')
]

orders/urls.py
from django.urls import path
from . import views
from . import ajax

app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/remove/', ajax.remove_from_cart, name="remove_from_cart"),
    path('cart/update_quantity/', ajax.update_quantity_cart, name="update_quantity_cart"),
    path("cart/update/",ajax.update_cart,name="update_cart")
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.IndexPageView.as_view(), name='index_page'),
    path('shop/', views.ShopPageView.as_view(), name='shop_page')
]

templates/inc/footer.html
{% load static %}
<!--newsletter section start-->
<section class="newsletter_section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="newsletter_inner d-flex justify-content-between align-items-center">
                    <div class="newsletter_text">
                        <h3>keep connected</h3>
                        <p>Get updates by subscribe our weekly newsletter</p>
                    </div>
                    <div class="newsletter_subscribe">
                        <form id="mc-form">
                            <input class="border-0" id="mc-email" type="email" autocomplete="off"
                                   placeholder="Enter your email address">
                            <i class="icon-envelope-open icons"></i>
                            <button class="border-0" id="mc-submit">Subscribe</button>
                        </form>
                        <!-- mailchimp-alerts Start -->
                        <div class="mailchimp-alerts text-centre">
                            <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                            <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                            <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                        </div><!-- mailchimp-alerts end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--newsletter section end-->
<!--footer area start-->
<footer class="footer_widgets">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-5 col-sm-5">
                <div class="footer_widget_list">
                    <div class="footer_logo">
                        <a href="#"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                    </div>
                    <div class="footer_contact">
                        <div class="footer_contact_list">
                            <span>Our Location</span>
                            <p>869 General Village Apt. 645, Moorebury, USA</p>
                        </div>
                        <div class="footer_contact_list">
                            <span>24/7 hotline:</span>
                            <a href="tel:(+99)0521282399">(+99) 052 128 2399</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-7">
                <div class="footer_widget_list text-right">
                    <div class="footer_menu">
                        <ul class="d-flex justify-content-end">
                            <li><a href="index.html">home</a></li>
                            <li><a href="shop.html">Shop</a></li>
                            <li><a href="product-details.html">Product</a></li>
                            <li><a href="#">pages</a></li>
                            <li><a href="blog.html">Blog</a></li>
                        </ul>
                    </div>
                    <div class="footer_social">
                        <ul class="d-flex justify-content-end">
                            <li><a href="https://twitter.com" data-tippy="Twitter" data-tippy-inertia="true"
                                   data-tippy-delay="50"
                                   data-tippy-arrow="true" data-tippy-placement="top"><i class="ion-social-twitter"></i></a>
                            </li>
                            <li><a href="https://www.facebook.com" data-tippy="Facebook" data-tippy-inertia="true"
                                   data-tippy-delay="50"
                                   data-tippy-arrow="true" data-tippy-placement="top"><i
                                    class="ion-social-facebook"></i></a></li>
                            <li><a href="https://www.google.com" data-tippy="googleplus" data-tippy-inertia="true"
                                   data-tippy-delay="50"
                                   data-tippy-arrow="true" data-tippy-placement="top"><i
                                    class="ion-social-googleplus-outline"></i></a></li>
                            <li><a href="https://www.instagram.com" data-tippy="Instagram" data-tippy-inertia="true"
                                   data-tippy-delay="50"
                                   data-tippy-arrow="true" data-tippy-placement="top"><i
                                    class="ion-social-instagram-outline"></i></a></li>
                            <li><a href="https://www.youtube.com" data-tippy="Youtube" data-tippy-inertia="true"
                                   data-tippy-delay="50"
                                   data-tippy-arrow="true" data-tippy-placement="top"><i class="ion-social-youtube"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="copyright_right">
                        <p>©2021 <span>Uthr</span>. made with <i class="ion-heart"></i> by <a
                                href="https://hasthemes.com" target="_blank">HasThemes</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--footer area end-->

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }} text-center text-black" role="alert">
            {{ message }}
        </p>
    {% endfor %}
{% endif %}

templates/inc/mini_cart.html
<div class="mini_cart">
    <div class="cart_gallery">
        <div class="cart_close">
            <div class="cart_text">
                <h3>cart</h3>
            </div>
            <div class="mini_cart_close">
                <a href="javascript:void(0)"><i class="icon-close icons"></i></a>
            </div>
        </div>
        {% for item in cart %}

            <div class="cart_item">
                <div class="cart_img">
                    <a href="#"><img src="{{ item.photo }}" alt=""></a>
                </div>
                <div class="cart_info">
                    <a href="#">{{ item.name }}</a>
                    <p class="d-inline">Size : {{ item.size }}</p>
                    <p class="d-inline ml-2" >Color : {{ item.color }}</p>
                    <p class="mt-3">Quantity : {{ item.quantity }} x <span> {{ item.price }} </span></p>
                    <p>Sub Total : <span> ${{ item.sub_total }} </span></p>
                </div>
                <div class="cart_remove">
                    <a href="#"><i class="icon-close icons"></i></a>
                </div>
            </div>
        {% endfor %}

    </div>
    <div class="mini_cart_table">
        <div class="cart_table_border">

            <div class="cart_total mt-10">
                <span>total price:</span>
                <span class="price">${{ cart.get_total_price }}</span>
            </div>
        </div>
    </div>
    <div class="mini_cart_footer">
        <div class="cart_button">
            <a href="{% url 'orders:cart' %}"><i class="fa fa-shopping-cart"></i> View cart</a>
        </div>
        <div class="cart_button">
            <a href="{% url 'orders:cart' %}"><i class="fa fa-sign-in"></i> Checkout</a>
        </div>
    </div>
</div>
<!--mini cart end-->

templates/inc/navbar.html
{% load mptt_tags %}

<header class="header_section header_transparent" style="position: absolute">
    <div class="header_top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="header_top_inner d-flex justify-content-between align-items-center">
                        <div class="header_contact_info">
                            <ul class="d-flex">
                                <li class="text-white"><i class="icons icon-phone"></i> <a
                                        href="tel:+989208292522">+98 920 829 2522</a></li>
                                <li class="text-white"><i class="icon-envelope-letter icons"></i> <a
                                        href="#">mehranmirzaeiv@domain.com</a></li>
                            </ul>
                        </div>
                        <div class="free_shipping_text">
                            <p class="text-white">Free shipping worldwide for orders over $99 </p>
                        </div>
                        <div class="header_top_sidebar d-flex align-items-center">
                            <div class="header_social d-flex">
                                <span>Follow us</span>
                                <ul class="d-flex">
                                    <li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
                                    <li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
                                    <li><a href="https://instagram.com/mehran20.56"><i
                                            class="icon-social-instagram icons"></i></a></li>
                                    <li><a href="#"><i class="icon-social-youtube icons"></i></a></li>
                                    <li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
                                </ul>
                            </div>
                            <div class="language_currency">
                                <ul class="d-flex">
                                    <li class="language"><a href="#"> Eng <i
                                            class="icon-right ion-ios-arrow-down"></i></a>
                                        <ul class="dropdown_language">
                                            <li><a href="#">Persian</a></li>
                                            <li><a href="#">Spanish</a></li>
                                            <li><a href="#">Russian</a></li>
                                        </ul>
                                    </li>
                                    <li class="currency"><a href="#">$ Toman <i
                                            class="icon-right ion-ios-arrow-down"></i></a>
                                        <ul class="dropdown_currency">
                                            <li><a href="#">$ US Dollar</a></li>
                                            <li><a href="#">€ Euro</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main_header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="header_container d-flex justify-content-between align-items-center">
                        <div class="canvas_open">
                            <a href="javascript:void(0)"><i class="ion-navicon"></i></a>
                        </div>
                        <div class="header_logo">
                            <a class="sticky_none" href="{% url 'pages:index_page' %}"><img
                                    src="../../static/img/logo/logo.png"
                                    alt=""></a>
                        </div>
                        <!--main menu start-->
                        <div class="main_menu d-none d-lg-block">
                            <nav>
                                <ul class="d-flex">
                                    {% recursetree menu %}
                                        <li class="nav-item">
                                            <a class="nav-link" href="{{ node.link }}">{{ node }}</a>
                                            {% if not node.is_leaf_node %}
                                                <ul class="sub_menu" style="top:55px;">
                                                    {{ children }}
                                                </ul>
                                            {% endif %}
                                        </li>
                                    {% endrecursetree %}
                                </ul>
                            </nav>
                        </div>
                        <div class="header_account">
                            <ul class="d-flex">
                                <li class="header_search"><a href="#"><i class="icon-magnifier icons"></i></a></li>
                                <li class="account_link"><a href="#"><i class="icon-user icons"></i></a>
                                    <ul class="dropdown_account_link">
                                        {% if not request.user.is_authenticated %}
                                            <li><a href="{% url 'accounts:accounts_login' %}">Login</a></li>
                                            <li><a href="{% url 'accounts:accounts_register' %}">Register</a></li>
                                        {% else %}
                                            <li><a href="#">My Account</a></li>
                                            <li><a href="#">My Orders</a></li>
                                            <li><a href="#">My Comments</a></li>
                                            <li><a href="{% url 'accounts:accounts_logout' %}">Logout</a></li>
                                        {% endif %}
                                    </ul>
                                </li>
                                <li><a href="#"><i class="icon-heart icons"></i></a> <span
                                        class="item_count">2</span></li>
                                <li class="shopping_cart"><a href="#"><i class="icon-basket-loaded icons"></i></a>
                                    <span id="cart_count" class="item_count">{{ cart.get_cart_counter }}</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- page search box -->
    <div class="page_search_box">
        <div class="search_close">
            <i class="ion-close-round"></i>
        </div>
        <form class="border-bottom" action="#">
            <input class="border-0" placeholder="Search products..." type="text">
            <button type="submit"><span class="icon-magnifier icons"></span></button>
        </form>
    </div>

</header>

templates/inc/offcanvas_menu.html
{% load mptt_tags %}

<!--offcanvas menu area start-->
<div class="body_overlay">
</div>
<div class="offcanvas_menu">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="offcanvas_menu_wrapper">
                    <div class="canvas_close">
                        <a href="javascript:void(0)"><i class="ion-android-close"></i></a>
                    </div>
                    <div class="header_contact_info">
                        <ul class="d-flex">
                            <li class="text-white"><i class="icons icon-phone"></i> <a href="tel:+0989208292522">+98
                                920 829 2522</a></li>
                            <li class="text-white"><i class="icon-envelope-letter icons"></i> <a
                                    href="#">mehranmirzaeiv@gmail.com</a></li>
                        </ul>
                    </div>
                    <div class="header_social d-flex">
                        <span>Follow us</span>
                        <ul class="d-flex">
                            <li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
                            <li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
                            <li><a href="#"><i class="icon-social-instagram icons"></i></a></li>
                            <li><a href="#"><i class="icon-social-youtube icons"></i></a></li>
                            <li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
                        </ul>
                    </div>
                    <div class="language_currency">
                        <ul class="d-flex">
                            <li class="language"><a href="#"> Eng <i class="icon-right ion-ios-arrow-down"></i></a>
                                <ul class="dropdown_language">
                                    <li><a href="#">French</a></li>
                                    <li><a href="#">Spanish</a></li>
                                    <li><a href="#">Russian</a></li>
                                </ul>
                            </li>
                            <li class="currency"><a href="#"> USd <i class="icon-right ion-ios-arrow-down"></i></a>
                                <ul class="dropdown_currency">
                                    <li><a href="#">€ Euro</a></li>
                                    <li><a href="#">£ Pound Sterling</a></li>
                                    <li><a href="#">$ US Dollar</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div id="menu" class="text-left ">
                        <ul class="offcanvas_main_menu">
                            {% recursetree menu %}
                                <li class="menu-item-has-children">
                                    <a href="{{ node.link }}">{{ node }}</a>
                                    {% if not node.is_leaf_node %}
                                        <ul class="sub-menu">
                                            {{ children }}
                                        </ul>
                                    {% endif %}
                                </li>
                            {% endrecursetree %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--offcanvas menu area end-->